version: "3.9"

services:
  stargate-api:
    build:
      context: ./stargate-api
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: stargate-api
    ports:
      - "5204:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Development
    working_dir: /app
    networks:
      - stargate-network

  stargate-ui:
    build:
      context: ./stargate-ui
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: stargate-ui
    ports:
      - "80:80"
    depends_on:
      - stargate-api
    networks:
      - stargate-network

networks:
  stargate-network:
    driver: bridge